#!/bin/sh
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0, which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the
# Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
# version 2 with the GNU Classpath Exception, which is available at
# https://www.gnu.org/software/classpath/license.html.
#
# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
#

# This is tricky
# "ui:" is found in many places in the documentation on the conf files.
# It is defined in the renderer conf files by the taglib-prefix.
# Make this an entity.
# Need to find out how it is passed to the tld generator.
# It looks like the "-p ui" option. These args are ant properties
# defined in webui/build.properties

newmodule="woodstock"
tagprefix="webuijsf"
#taguri="http://jvnet.org/webui/${tagprefix}"
taguri="http://www.sun.com/webui/${tagprefix}"


### Fix up lockhart/example jsp's ###

cd $newmodule/lockhart/example/web
for f in `find . -name \*.jsp -print` ; do

    sed -e 's?ui="http://www.sun.com/web/ui"?'${tagprefix}'="'${taguri}'"?' \
	-e 's?uri="http://www.sun.com/web/ui"?uri="'${taguri}'"?' \
	-e 's?prefix="ui"?prefix="'${tagprefix}'"?' \
	-e 's?<ui:?<'${tagprefix}':?g' \
	-e 's?</ui:?</'${tagprefix}':?g' \
	-e 's?lt;ui:?lt;'${tagprefix}':?g' \
	-e 's?lt;/ui:?lt;/'${tagprefix}':?g' \
	-e 's? ui:? '${tagprefix}':?g' $f > /tmp/junk

    mv /tmp/junk $f

done
